import { test, expect, type Page } from '@playwright/test';
import { createIrcClient, type IrcClient } from '../irc-client';
import { connectViaWizard } from '../helpers';

/**
 * A channel is one channel however it is cased. Reported by a user: their
 * sidebar held two "#religie" entries - one collecting only the system
 * messages, the other the actual chat - and removing either left the other
 * behind. The client held the casing the user typed (or restored from storage)
 * while the server answered with its own canonical one, and the two never met.
 *
 * Ergo canonicalises channel names on everything it relays, so the mismatch
 * cannot be produced from the wire here; it is seeded through the persisted
 * store instead, which is where affected users carry it in from.
 */

/** The casing the bot creates the channel with - what the server will echo */
const SERVER_CASING = '#CasingTest';
/** The casing the user typed */
const USER_CASING = '#casingtest';

/** Overwrite the persisted channel store, as a build without the fix left it */
const seedChannelStore = async (page: Page, state: unknown, version: number): Promise<void> => {
  await page.evaluate(async ({ state, version }) => {
    const settings = JSON.parse(localStorage.getItem('sic-settings') ?? '{}') as {
      state?: { server?: { network: string; servers: string[]; default: number } };
    };
    const server = settings.state?.server;
    if (!server) {
      throw new Error('no server in sic-settings - the wizard did not complete');
    }
    const key = `sic-channels:${server.network}:${server.servers[server.default]}`;
    const record = JSON.stringify({ state, version });

    // idb-keyval's defaults: database "keyval-store", object store "keyval"
    await new Promise<void>((resolve, reject) => {
      const open = indexedDB.open('keyval-store');
      open.onerror = () => reject(open.error);
      open.onsuccess = () => {
        const db = open.result;
        const tx = db.transaction('keyval', 'readwrite');
        tx.objectStore('keyval').put(record, key);
        tx.oncomplete = () => { db.close(); resolve(); };
        tx.onerror = () => reject(tx.error);
      };
    });
  }, { state, version });
};

const persistedChannel = (name: string, messages: { id: string; text: string; time: string }[] = []) => ({
  name,
  category: 'channel',
  unReadMessages: 0,
  messages: messages.map((message) => ({
    id: message.id,
    message: message.text,
    target: name,
    time: message.time,
    category: 'info',
  })),
  topic: '',
  topicSetBy: '',
  topicSetTime: 0,
  typing: [],
});

let bot: IrcClient;
let sharedPage: Page;

test.beforeAll(async ({ browser }) => {
  bot = await createIrcClient('casingbot');
  await bot.join(SERVER_CASING);
  await bot.setTopic(SERVER_CASING, 'One channel, one window');

  sharedPage = await browser.newPage();
  await sharedPage.goto('/');
  await connectViaWizard(sharedPage, 'casing-tester');
});

test.afterAll(async () => {
  await sharedPage.close();
  bot.disconnect();
});

test.describe('Channel name casing', () => {
  test.describe.configure({ mode: 'serial' });

  test('joining in another casing opens one window under the server name', async () => {
    const channelNav = sharedPage.getByTestId('channels-sidebar');

    await sharedPage.locator('#message-input').fill(`/join ${USER_CASING}`);
    await sharedPage.locator('#message-input').press('Enter');

    // The server's casing wins in the UI...
    await expect(channelNav.getByRole('button', { name: SERVER_CASING, exact: true })).toBeVisible({ timeout: 10_000 });

    // ...and there is exactly one entry, not one per casing
    await expect(channelNav.getByRole('button', { name: /^#casingtest$/i })).toHaveCount(1);
  });

  test('chat and system messages land in the same window', async () => {
    const channelNav = sharedPage.getByTestId('channels-sidebar');
    await channelNav.getByRole('button', { name: SERVER_CASING, exact: true }).click();

    // The join notice is generated by the client, the chat comes from the
    // server - the bug put these two in separate windows
    await expect(sharedPage.getByText(/casing-tester/).first()).toBeVisible({ timeout: 10_000 });

    bot.sendMessage(SERVER_CASING, 'chat lands here');
    await expect(sharedPage.getByText('chat lands here')).toBeVisible({ timeout: 10_000 });

    await expect(sharedPage.getByTestId('topic-display')).toHaveText('One channel, one window', { timeout: 10_000 });
    await expect(channelNav.getByRole('button', { name: /^#casingtest$/i })).toHaveCount(1);
  });

  test('removing the channel removes it for good', async () => {
    const channelNav = sharedPage.getByTestId('channels-sidebar');

    // The previous test's .click() on this exact row already left the cursor
    // resting on it, so hovering the same coordinates again dispatches no new
    // mouseenter and the reveal-on-hover close icon never appears. Move away
    // first so this hover is a genuine pointer entry.
    await sharedPage.mouse.move(0, 0);
    await channelNav.getByRole('button', { name: SERVER_CASING, exact: true }).hover();
    await channelNav.getByRole('button', { name: `Leave ${SERVER_CASING}` }).click();

    // No leftover under any casing
    await expect(channelNav.getByRole('button', { name: /^#casingtest$/i })).toHaveCount(0);
    await expect(sharedPage.locator('#message-input')).not.toHaveAttribute('placeholder', /casingtest/i);
  });

  // The reload tests come last: each one leaves the client disconnected
  test('case-duplicate windows left by older versions are merged on load', async () => {
    const channelNav = sharedPage.getByTestId('channels-sidebar');

    // Let any pending persist write flush before we overwrite the record
    await sharedPage.waitForTimeout(2_500);

    // Exactly what an affected user has in storage: the same channel twice,
    // one window holding the system messages and the other the chat, written
    // under the pre-fix schema version
    await seedChannelStore(sharedPage, {
      openChannels: [
        persistedChannel('#seeded', [{ id: 'sys-1', text: 'seeded system message', time: '2026-07-30T10:00:00.000Z' }]),
        persistedChannel('#Seeded', [{ id: 'chat-1', text: 'seeded chat message', time: '2026-07-30T11:00:00.000Z' }]),
      ],
      openChannelsShortList: [
        { name: '#seeded', category: 'channel', unReadMessages: 0 },
        { name: '#Seeded', category: 'channel', unReadMessages: 0 },
      ],
    }, 1);

    await sharedPage.reload();

    // One window, under the name of the first of the two
    await expect(channelNav.getByRole('button', { name: /^#seeded$/i })).toHaveCount(1, { timeout: 10_000 });

    // ...holding what had been split across both
    await channelNav.getByRole('button', { name: '#seeded', exact: true }).click();
    await expect(sharedPage.getByText('seeded system message')).toBeVisible({ timeout: 10_000 });
    await expect(sharedPage.getByText('seeded chat message')).toBeVisible({ timeout: 10_000 });
  });

  test('a window restored under a stale casing is adopted, not duplicated', async () => {
    const channelNav = sharedPage.getByTestId('channels-sidebar');

    await sharedPage.waitForTimeout(2_500);

    // A single window under the casing the user typed. On reconnect the client
    // rejoins it and the server answers with its own casing - which used to
    // open a second window that then only ever received the system broadcasts.
    await seedChannelStore(sharedPage, {
      openChannels: [persistedChannel(USER_CASING)],
      openChannelsShortList: [{ name: USER_CASING, category: 'channel', unReadMessages: 0 }],
    }, 1);

    await sharedPage.reload();

    await expect(channelNav.getByRole('button', { name: /^#casingtest$/i })).toHaveCount(1, { timeout: 10_000 });

    // Reconnect so the client rejoins the channel from the restored list
    await sharedPage.getByRole('button', { name: 'Connect' }).click();

    // The server's casing is adopted by the window we already had
    await expect(channelNav.getByRole('button', { name: SERVER_CASING, exact: true })).toBeVisible({ timeout: 20_000 });
    await expect(channelNav.getByRole('button', { name: /^#casingtest$/i })).toHaveCount(1);

    // ...and it is the live window: the topic and new chat arrive in it
    await channelNav.getByRole('button', { name: SERVER_CASING, exact: true }).click();
    await expect(sharedPage.getByTestId('topic-display')).toHaveText('One channel, one window', { timeout: 10_000 });

    bot.sendMessage(SERVER_CASING, 'after the rejoin');
    await expect(sharedPage.getByText('after the rejoin')).toBeVisible({ timeout: 10_000 });
  });
});
