import { BUILTIN_LAYOUT_CSS, type BuiltinThemeId } from './builtinThemes';
import { buildPaletteCss, DEFAULT_DARK_COLORS, DEFAULT_LIGHT_COLORS, MSG_COLOR_KEYS, type MsgColorPalette } from './palette';

// Convenience re-exports for Creator consumers (dialog, tests)
export { DEFAULT_DARK_COLORS, DEFAULT_LIGHT_COLORS, MSG_COLOR_KEYS } from './palette';
export type { MsgColorKey, MsgColorPalette } from './palette';

/**
 * The Theme Creator is a no-CSS-required way to build a theme: it turns a
 * structured settings object into a full theme stylesheet (base layout +
 * message-color palette + a few layout toggles). The settings are embedded in
 * the generated CSS as a marker comment so the Creator can re-open a theme it
 * generated and restore the controls.
 */

export interface ThemeCreatorSettings {
  base: BuiltinThemeId;
  showSeconds: boolean;
  showAvatars: boolean; // only affects the modern base
  showEmbeds: boolean;
  compact: boolean;
  colors: {
    light: MsgColorPalette;
    dark: MsgColorPalette;
  };
}

export const defaultCreatorSettings = (base: BuiltinThemeId = 'modern'): ThemeCreatorSettings => ({
  base,
  showSeconds: false,
  showAvatars: true,
  showEmbeds: true,
  compact: false,
  colors: {
    light: { ...DEFAULT_LIGHT_COLORS },
    dark: { ...DEFAULT_DARK_COLORS },
  },
});

const CREATOR_MARKER_PREFIX = '/* sic-creator:1 ';
const CREATOR_MARKER_SUFFIX = ' */';
const CREATOR_MARKER_RE = /^\/\* sic-creator:1 (\{.*\}) \*\//;

export const generateThemeCss = (settings: ThemeCreatorSettings): string => {
  const parts: string[] = [];

  parts.push(`${CREATOR_MARKER_PREFIX}${JSON.stringify(settings)}${CREATOR_MARKER_SUFFIX}`);
  parts.push('/* Generated by the Theme Creator — editing below is fine, but re-saving');
  parts.push('   from the Creator regenerates this file from the settings above. */');
  parts.push('');
  parts.push(BUILTIN_LAYOUT_CSS[settings.base].trimEnd());
  parts.push('');
  parts.push(buildPaletteCss(settings.colors.light, settings.colors.dark));

  const optionRules: string[] = [];
  if (settings.showSeconds) {
    optionRules.push('.sic-msg-time-seconds { display: inline; }');
  }
  if (!settings.showAvatars && settings.base === 'modern') {
    optionRules.push('.sic-msg-gutter { display: none; }');
  }
  if (!settings.showEmbeds) {
    optionRules.push('.sic-msg-embeds { display: none; }');
  }
  if (settings.compact) {
    // Repeat the base selectors so this beats the base rules' specificity
    optionRules.push('.sic-msg, .sic-msg:not([data-content]), .sic-msg[data-grouped] { padding-top: 0; padding-bottom: 0; }');
  }
  if (optionRules.length > 0) {
    parts.push('', '/* Creator options */', ...optionRules);
  }

  return `${parts.join('\n')}\n`;
};

const isPalette = (value: unknown): value is MsgColorPalette =>
  typeof value === 'object' && value !== null && MSG_COLOR_KEYS.every((key) => typeof (value as Record<string, unknown>)[key] === 'string');

/**
 * Extracts Creator settings from CSS previously produced by generateThemeCss.
 * Returns null for hand-written CSS (no marker) or an unreadable marker.
 */
export const parseCreatorSettings = (css: string): ThemeCreatorSettings | null => {
  const match = CREATOR_MARKER_RE.exec(css);
  if (!match?.[1]) { return null; }
  try {
    const parsed = JSON.parse(match[1]) as Partial<ThemeCreatorSettings>;
    if (
      (parsed.base !== 'classic' && parsed.base !== 'modern') ||
      typeof parsed.showSeconds !== 'boolean' ||
      typeof parsed.showAvatars !== 'boolean' ||
      typeof parsed.showEmbeds !== 'boolean' ||
      typeof parsed.compact !== 'boolean' ||
      !isPalette(parsed.colors?.light) ||
      !isPalette(parsed.colors?.dark)
    ) {
      return null;
    }
    return parsed as ThemeCreatorSettings;
  } catch {
    return null;
  }
};
