import { readFileSync } from 'node:fs';
import { type Page } from '@playwright/test';
import { PASSWORD_FILE } from './global-setup';

/**
 * Wrap `WebSocket` on the page so a test can force every live socket closed,
 * simulating a connection drop (Wi-Fi/cellular handoff, server hiccup) without
 * touching the page itself. Must be called before `page.goto`.
 *
 * Exposes `window.__closeAllWS()` — closes every OPEN/CONNECTING socket and
 * returns `{ total, closed }`. Same technique the reconnect specs already use
 * inline; shared here so the mobile-reconnect and e2ee-reconnect specs agree on
 * it. Playwright's own `context.setOffline` is avoided on purpose: it doesn't
 * reliably surface a `close` event to the app on every browser.
 */
export const installWebSocketKillSwitch = async (page: Page): Promise<void> => {
  await page.addInitScript(() => {
    const OrigWS = globalThis.WebSocket;
    const allSockets: WebSocket[] = [];

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (globalThis as any).WebSocket = function (url: string, protocols?: string | string[]) {
      const ws = protocols ? new OrigWS(url, protocols) : new OrigWS(url);
      allSockets.push(ws);
      return ws;
    };
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (globalThis as any).WebSocket.prototype = OrigWS.prototype;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (globalThis as any).WebSocket.CONNECTING = OrigWS.CONNECTING;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (globalThis as any).WebSocket.OPEN = OrigWS.OPEN;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (globalThis as any).WebSocket.CLOSING = OrigWS.CLOSING;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (globalThis as any).WebSocket.CLOSED = OrigWS.CLOSED;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (globalThis as any).__closeAllWS = () => {
      let closed = 0;
      for (const ws of allSockets) {
        if (ws.readyState === OrigWS.OPEN || ws.readyState === OrigWS.CONNECTING) {
          ws.close();
          closed++;
        }
      }
      return { total: allSockets.length, closed };
    };
  });
};

/** Force every live WebSocket on the page closed (see `installWebSocketKillSwitch`). */
export const dropConnection = async (page: Page): Promise<void> => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await page.evaluate(() => (globalThis as any).__closeAllWS());
};

const ERGO_HOST = 'localhost';
// Port 6697 is blocked by Chrome (ERR_UNSAFE_PORT); use 8097 instead
const ERGO_WSS_PORT = '8097';

/** Read the random server password generated by global-setup */
export const getServerPassword = (): string => readFileSync(PASSWORD_FILE, 'utf8');

/**
 * Go through the wizard to connect to the local ergo server.
 * Enters nick, custom server (localhost WebSocket), server password,
 * and either joins specified channels or skips the channel step.
 */
export const connectViaWizard = async (
  page: Page,
  nick: string,
  options: { channels?: string[] } = {},
): Promise<void> => {
  // Step 1: Nick
  await page.getByLabel('Enter your nickname').fill(nick);
  await page.getByRole('button', { name: 'Next' }).click();

  // Step 2: Server - enter custom WebSocket server
  await page.getByLabel('Server address').fill(ERGO_HOST);
  await page.getByLabel('Port').clear();
  await page.getByLabel('Port').fill(ERGO_WSS_PORT);

  // Select WebSocket connection type
  await page.getByRole('button', { name: 'WebSocket' }).click();

  // Enter server password
  await page.getByLabel('Server password').fill(getServerPassword());

  // Submit (this triggers connection + goes to loading step)
  await page.getByRole('button', { name: 'Next' }).click();

  // Step 3: Loading - wait for connection and password check (≈5 seconds)
  await page.getByText('Connected').waitFor({ timeout: 15_000 });

  // Wait for the channels step to appear (after ~5s password check)
  await page.getByText('Select a irc channel').waitFor({ timeout: 15_000 });

  // Step 4: Channels - join or skip
  if (options.channels && options.channels.length > 0) {
    // Wait for channel list to finish loading
    await page.getByText('Downloading channels list').waitFor({ state: 'hidden', timeout: 15_000 });

    // Select each channel by clicking its row. The row's accessible name is
    // "<channel> <users> <topic>", so match it anchored at the start to avoid
    // one channel name being a substring of another (e.g. #settings vs.
    // #chan-settings).
    for (const channel of options.channels) {
      const escaped = channel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      await page.getByRole('button', { name: new RegExp(`^${escaped}(\\s|$)`) }).click();
    }
    await page.getByRole('button', { name: 'Next' }).click();
  } else {
    await page.getByRole('button', { name: 'Skip' }).click();
  }

  // Wait for main page to render
  await page.locator('#message-input').waitFor({ timeout: 10_000 });
};
